apiVersion: policy.open-cluster-management.io/v1
kind: PolicyGenerator
metadata:
  name: policy-generator-security-fix-checks
policyDefaults:
  namespace: policy-generator-blog
  remediationAction: inform
  severity: medium
policies:
  - name: security-fix-checks
    manifests:
      - path: security-fix-checks-manifests
